spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: mypassword
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false


indexing-settings:
  sites:
    - url: https://lenta.ru
      name: Лента.ру
    - url: http://radiomv.ru
      name: radiomv
    - url: https://playback.ru
      name: PlayBack.Ru
    - url: https://skillbox.ru
      name: Skillbox
    - url: https://lentaerrorurl.ru
      name: LentaError

connection-settings:
  userAgent: Mozilla/5.0 (X11; Fedora;Linux x86; rv:60.0) Gecko/20100101 Firefox/60.0
  referer: https://www.google.com